# Generated by Django 6.0.1 on 2026-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartuser_paymentmethod_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='is_paid',
            new_name='isPaid',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='paymongo_id',
            new_name='paymongopayment',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='paymongo_status',
            new_name='paymongostatus',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='total_price',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullname',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='payment',
            new_name='paymentId',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
